# Generated by Django 2.2.6 on 2019-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(choices=[(0, 'red'), (1, 'blue'), (2, 'green')], default=0, max_length=50),
        ),
    ]
