# Generated by Django 2.2.6 on 2019-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_cars_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.PositiveIntegerField(choices=[(1, 'red'), (2, 'blue'), (3, 'green')], default=0, max_length=50),
        ),
    ]
